project:
  type: book

book:
  title: "QM1-Tutorium"
  author: "Raphael Balzer, Emilia Braun, Finn Weber"
  date: "3/28/2023"
  search:
    location: sidebar
    type: textbox
  sidebar: 
    logo: QM1-Tutorium_logo.png
    border: false
  navbar:
    left:
      - text: "statistik1"
        href: https://statistik1.netlify.app/
      - text: "start: bayes!"
        href: https://start-bayes.netlify.app/
      - text: "QM1-Tutorium"
        href: https://qm1-tutorium.netlify.app/
      - text: "QM2-Tutorium"
        href: https://qm2-tutorium.netlify.app/
  chapters:
    - index.qmd
    - part: "R kennenlernen"
      chapters: 
        - Aufgaben1.qmd
        - Lösungen1.qmd
    - part: "Data Wrangling"
      chapters: 
        - Aufgaben_Dinos.qmd
        - Lösungen_Dinos.qmd
        - Aufgaben_plague.qmd
        - Lösungen_plague.qmd
    - part: "Fallstudien EDA"
      chapters: 
        - QM1_Tutorium_Fallstudie_IRIS.qmd
        - Iris_eda_teil2.qmd
    - part: "Fallstudien Modellierung"
      chapters:
        - iris_lm.qmd
        - Probeklausur.qmd
    - part: "Fallstudien Aufgaben"
      chapters:
        - QM1_Tut_Fallstudie_Penguins_Aufg.qmd
        - QM1_Tut_Fallstudie_Penguins_Loes.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: minty
      dark: vapor
    df-print: paged
  pdf:
    documentclass: scrreprt

editor: visual