project:
  type: book

book:
  title: "QM1-Tutorium SoSe23"
  author: "Raphael Balzer, Finn Weber"
  date: "3/28/2023"
  chapters:
    - index.qmd
    - part: "R kennenlernen"
      chapters: 
        - Aufgaben1.qmd
        - Lösungen1.qmd
    - part: "Data Wrangling"
      chapters: 
        - Aufgaben_Dinos.qmd
        - Lösungen_Dinos.qmd
        - Aufgaben_plague.qmd
        - Lösungen_plague.qmd
    - part: "Fallstudien"
      chapters: 
        - QM1_Tutorium_Fallstudie_IRIS.qmd
        - Iris_eda_teil2.qmd
        - iris_lm.qmd
        - QM1_Tut_Fallstudie_Penguins_Aufg.qmd
        - QM1_Tut_Fallstudie_Penguins_Loes.qmd
        - Probeklausur.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: litera
      dark: slate
    df-print: paged
  pdf:
    documentclass: scrreprt

editor: visual