# Lösungen Dinojudo

## Lösung 1 
```{r}
# Aufgabe 1 

library(tidyverse)

#1.1
library(readr)
Jurassic_Park <- read_csv("Jurassic_Park.csv")

#1.2
head(Jurassic_Park, n = 10)

#1.3
tail(Jurassic_Park, n = 10)
```

## Lösung 2
```{r}
# Aufgabe 2

#2.1
Jurassic_Park2 <- Jurassic_Park %>% 
  select(name, diet,lived_in,type,Length, species, named_by)

#2.2
Jurassic_Park2 %>% 
  arrange(-Length) -> Jurassic_Park2

#2.3
Jurassic_Park2 %>% 
  count(Length > 7.5)

```
## Lösung 3
```{r}
# Aufgabe 3

#3.1
Jurassic_Park %>% 
  summarise(mean(Length))

#3.2
Jurassic_Park %>% 
  count(diet)

#3.3
Jurassic_Park2 %>% 
  select(named_by, name) %>% 
  filter(name == "gobisaurus")
```
## Lösung 4
```{r}
#4.1
Jurassic_Park %>% 
  group_by(diet) %>% 
  summarise(mean(Length))

#4.2
Jurassic_Park %>% 
  select(type, lived_in) %>% 
  filter(type == "armoured dinosaur") %>% 
  count(lived_in)

#4.3
Jurassic_Park %>% 
  select(Length, type) %>% 
  filter(type == "small theropod") %>% 
  arrange(Length)

#4.4
Jurassic_Park %>% 
  select(diet, lived_in) %>%
  filter(lived_in == "USA") %>% 
  count(diet)
```
## Lösung 5
```{r}
# Dino1
Jurassic_Park %>% 
  select(type, diet, lived_in, Length) %>% 
  filter(lived_in == "North Africa",
         type == "large theropod",
         diet == "carnivorous") %>%
  summarise(mean(Length))

# Dino2
Jurassic_Park %>% 
  select(type, diet, lived_in, Length) %>% 
  filter(lived_in == "China",
         type == "sauropod",
         diet == "herbivorous") %>%
  summarise(mean(Length))

```